require ('prototypes/items/beacon2.lua')
require ('prototypes/items/beacon3.lua')
require ('prototypes/entities/beacon2.lua')
require ('prototypes/entities/beacon3.lua')
require ('recipes/beacon2.lua')
require ('recipes/beacon3.lua')
require ('prototypes/research/effecttransmission2.lua')
require ('prototypes/research/effecttransmission3.lua')